#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor


_MEMCACHESERVICEERROR_ERRORCODE = descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='appengine_api.MemcacheServiceError.ErrorCode',
  filename='ErrorCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)

_MEMCACHESETREQUEST_SETPOLICY = descriptor.EnumDescriptor(
  name='SetPolicy',
  full_name='appengine_api.MemcacheSetRequest.SetPolicy',
  filename='SetPolicy',
  values=[
    descriptor.EnumValueDescriptor(
      name='SET', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REPLACE', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_MEMCACHESETRESPONSE_SETSTATUSCODE = descriptor.EnumDescriptor(
  name='SetStatusCode',
  full_name='appengine_api.MemcacheSetResponse.SetStatusCode',
  filename='SetStatusCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='STORED', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOT_STORED', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_MEMCACHEDELETERESPONSE_DELETESTATUSCODE = descriptor.EnumDescriptor(
  name='DeleteStatusCode',
  full_name='appengine_api.MemcacheDeleteResponse.DeleteStatusCode',
  filename='DeleteStatusCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='DELETED', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)

_MEMCACHEINCREMENTREQUEST_DIRECTION = descriptor.EnumDescriptor(
  name='Direction',
  full_name='appengine_api.MemcacheIncrementRequest.Direction',
  filename='Direction',
  values=[
    descriptor.EnumValueDescriptor(
      name='INCREMENT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DECREMENT', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_MEMCACHESERVICEERROR = descriptor.Descriptor(
  name='MemcacheServiceError',
  full_name='appengine_api.MemcacheServiceError',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MEMCACHESERVICEERROR_ERRORCODE,
  ],
  options=None)


_MEMCACHEGETREQUEST = descriptor.Descriptor(
  name='MemcacheGetRequest',
  full_name='appengine_api.MemcacheGetRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='appengine_api.MemcacheGetRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHEGETRESPONSE_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='appengine_api.MemcacheGetResponse.Item',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='appengine_api.MemcacheGetResponse.Item.key', index=0,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='appengine_api.MemcacheGetResponse.Item.value', index=1,
      number=3, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='appengine_api.MemcacheGetResponse.Item.flags', index=2,
      number=4, type=7, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MEMCACHEGETRESPONSE = descriptor.Descriptor(
  name='MemcacheGetResponse',
  full_name='appengine_api.MemcacheGetResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item', full_name='appengine_api.MemcacheGetResponse.item', index=0,
      number=1, type=10, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHESETREQUEST_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='appengine_api.MemcacheSetRequest.Item',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='appengine_api.MemcacheSetRequest.Item.key', index=0,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='appengine_api.MemcacheSetRequest.Item.value', index=1,
      number=3, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='appengine_api.MemcacheSetRequest.Item.flags', index=2,
      number=4, type=7, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='set_policy', full_name='appengine_api.MemcacheSetRequest.Item.set_policy', index=3,
      number=5, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expiration_time', full_name='appengine_api.MemcacheSetRequest.Item.expiration_time', index=4,
      number=6, type=7, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MEMCACHESETREQUEST = descriptor.Descriptor(
  name='MemcacheSetRequest',
  full_name='appengine_api.MemcacheSetRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item', full_name='appengine_api.MemcacheSetRequest.item', index=0,
      number=1, type=10, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MEMCACHESETREQUEST_SETPOLICY,
  ],
  options=None)


_MEMCACHESETRESPONSE = descriptor.Descriptor(
  name='MemcacheSetResponse',
  full_name='appengine_api.MemcacheSetResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='set_status', full_name='appengine_api.MemcacheSetResponse.set_status', index=0,
      number=1, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MEMCACHESETRESPONSE_SETSTATUSCODE,
  ],
  options=None)


_MEMCACHEDELETEREQUEST_ITEM = descriptor.Descriptor(
  name='Item',
  full_name='appengine_api.MemcacheDeleteRequest.Item',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='appengine_api.MemcacheDeleteRequest.Item.key', index=0,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_time', full_name='appengine_api.MemcacheDeleteRequest.Item.delete_time', index=1,
      number=3, type=7, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MEMCACHEDELETEREQUEST = descriptor.Descriptor(
  name='MemcacheDeleteRequest',
  full_name='appengine_api.MemcacheDeleteRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='item', full_name='appengine_api.MemcacheDeleteRequest.item', index=0,
      number=1, type=10, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHEDELETERESPONSE = descriptor.Descriptor(
  name='MemcacheDeleteResponse',
  full_name='appengine_api.MemcacheDeleteResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='delete_status', full_name='appengine_api.MemcacheDeleteResponse.delete_status', index=0,
      number=1, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MEMCACHEDELETERESPONSE_DELETESTATUSCODE,
  ],
  options=None)


_MEMCACHEINCREMENTREQUEST = descriptor.Descriptor(
  name='MemcacheIncrementRequest',
  full_name='appengine_api.MemcacheIncrementRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='appengine_api.MemcacheIncrementRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delta', full_name='appengine_api.MemcacheIncrementRequest.delta', index=1,
      number=2, type=4, cpp_type=4, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='direction', full_name='appengine_api.MemcacheIncrementRequest.direction', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MEMCACHEINCREMENTREQUEST_DIRECTION,
  ],
  options=None)


_MEMCACHEINCREMENTRESPONSE = descriptor.Descriptor(
  name='MemcacheIncrementResponse',
  full_name='appengine_api.MemcacheIncrementResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='new_value', full_name='appengine_api.MemcacheIncrementResponse.new_value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHEFLUSHREQUEST = descriptor.Descriptor(
  name='MemcacheFlushRequest',
  full_name='appengine_api.MemcacheFlushRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHEFLUSHRESPONSE = descriptor.Descriptor(
  name='MemcacheFlushResponse',
  full_name='appengine_api.MemcacheFlushResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHESTATSREQUEST = descriptor.Descriptor(
  name='MemcacheStatsRequest',
  full_name='appengine_api.MemcacheStatsRequest',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MERGEDNAMESPACESTATS = descriptor.Descriptor(
  name='MergedNamespaceStats',
  full_name='appengine_api.MergedNamespaceStats',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hits', full_name='appengine_api.MergedNamespaceStats.hits', index=0,
      number=1, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='misses', full_name='appengine_api.MergedNamespaceStats.misses', index=1,
      number=2, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='byte_hits', full_name='appengine_api.MergedNamespaceStats.byte_hits', index=2,
      number=3, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='items', full_name='appengine_api.MergedNamespaceStats.items', index=3,
      number=4, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes', full_name='appengine_api.MergedNamespaceStats.bytes', index=4,
      number=5, type=4, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='oldest_item_age', full_name='appengine_api.MergedNamespaceStats.oldest_item_age', index=5,
      number=6, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHESTATSRESPONSE = descriptor.Descriptor(
  name='MemcacheStatsResponse',
  full_name='appengine_api.MemcacheStatsResponse',
  filename='t/autogen/memcache.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='stats', full_name='appengine_api.MemcacheStatsResponse.stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MEMCACHEGETRESPONSE.fields_by_name['item'].message_type = _MEMCACHEGETRESPONSE_ITEM
_MEMCACHESETREQUEST_ITEM.fields_by_name['set_policy'].enum_type = _MEMCACHESETREQUEST_SETPOLICY
_MEMCACHESETREQUEST.fields_by_name['item'].message_type = _MEMCACHESETREQUEST_ITEM
_MEMCACHESETRESPONSE.fields_by_name['set_status'].enum_type = _MEMCACHESETRESPONSE_SETSTATUSCODE
_MEMCACHEDELETEREQUEST.fields_by_name['item'].message_type = _MEMCACHEDELETEREQUEST_ITEM
_MEMCACHEDELETERESPONSE.fields_by_name['delete_status'].enum_type = _MEMCACHEDELETERESPONSE_DELETESTATUSCODE
_MEMCACHEINCREMENTREQUEST.fields_by_name['direction'].enum_type = _MEMCACHEINCREMENTREQUEST_DIRECTION
_MEMCACHESTATSRESPONSE.fields_by_name['stats'].message_type = _MERGEDNAMESPACESTATS

class MemcacheServiceError(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHESERVICEERROR

class MemcacheGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEGETREQUEST

class MemcacheGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Item(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MEMCACHEGETRESPONSE_ITEM
  DESCRIPTOR = _MEMCACHEGETRESPONSE

class MemcacheSetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Item(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MEMCACHESETREQUEST_ITEM
  DESCRIPTOR = _MEMCACHESETREQUEST

class MemcacheSetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHESETRESPONSE

class MemcacheDeleteRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Item(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MEMCACHEDELETEREQUEST_ITEM
  DESCRIPTOR = _MEMCACHEDELETEREQUEST

class MemcacheDeleteResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEDELETERESPONSE

class MemcacheIncrementRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEINCREMENTREQUEST

class MemcacheIncrementResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEINCREMENTRESPONSE

class MemcacheFlushRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEFLUSHREQUEST

class MemcacheFlushResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHEFLUSHRESPONSE

class MemcacheStatsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHESTATSREQUEST

class MergedNamespaceStats(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MERGEDNAMESPACESTATS

class MemcacheStatsResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMCACHESTATSRESPONSE


_MEMCACHESERVICE = descriptor.ServiceDescriptor(
  name='MemcacheService',
  full_name='appengine_api.MemcacheService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='Get',
    full_name='appengine_api.MemcacheService.Get',
    index=0,
    containing_service=None,
    input_type=_MEMCACHEGETREQUEST,
    output_type=_MEMCACHEGETRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Set',
    full_name='appengine_api.MemcacheService.Set',
    index=1,
    containing_service=None,
    input_type=_MEMCACHESETREQUEST,
    output_type=_MEMCACHESETRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Delete',
    full_name='appengine_api.MemcacheService.Delete',
    index=2,
    containing_service=None,
    input_type=_MEMCACHEDELETEREQUEST,
    output_type=_MEMCACHEDELETERESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Increment',
    full_name='appengine_api.MemcacheService.Increment',
    index=3,
    containing_service=None,
    input_type=_MEMCACHEINCREMENTREQUEST,
    output_type=_MEMCACHEINCREMENTRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='FlushAll',
    full_name='appengine_api.MemcacheService.FlushAll',
    index=4,
    containing_service=None,
    input_type=_MEMCACHEFLUSHREQUEST,
    output_type=_MEMCACHEFLUSHRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Stats',
    full_name='appengine_api.MemcacheService.Stats',
    index=5,
    containing_service=None,
    input_type=_MEMCACHESTATSREQUEST,
    output_type=_MEMCACHESTATSRESPONSE,
    options=None,
  ),
])

class MemcacheService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MEMCACHESERVICE
class MemcacheService_Stub(MemcacheService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MEMCACHESERVICE

