#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
import descriptor_pb2

_FOREIGNENUM = descriptor.EnumDescriptor(
  name='ForeignEnum',
  full_name='protobuf_unittest.ForeignEnum',
  filename='ForeignEnum',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOREIGN_FOO', index=0, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FOREIGN_BAR', index=1, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FOREIGN_BAZ', index=2, number=6,
      options=None,
      type=None),
  ],
  options=None,
)


_TESTENUMWITHDUPVALUE = descriptor.EnumDescriptor(
  name='TestEnumWithDupValue',
  full_name='protobuf_unittest.TestEnumWithDupValue',
  filename='TestEnumWithDupValue',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOO1', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAR1', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FOO2', index=3, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAR2', index=4, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_TESTSPARSEENUM = descriptor.EnumDescriptor(
  name='TestSparseEnum',
  full_name='protobuf_unittest.TestSparseEnum',
  filename='TestSparseEnum',
  values=[
    descriptor.EnumValueDescriptor(
      name='SPARSE_A', index=0, number=123,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_B', index=1, number=62374,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_C', index=2, number=12589234,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_D', index=3, number=-15,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_E', index=4, number=-53452,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_F', index=5, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPARSE_G', index=6, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


FOREIGN_FOO = 4
FOREIGN_BAR = 5
FOREIGN_BAZ = 6
FOO1 = 1
BAR1 = 2
BAZ = 3
FOO2 = 1
BAR2 = 2
SPARSE_A = 123
SPARSE_B = 62374
SPARSE_C = 12589234
SPARSE_D = -15
SPARSE_E = -53452
SPARSE_F = 0
SPARSE_G = 2


_TESTALLTYPES_NESTEDENUM = descriptor.EnumDescriptor(
  name='NestedEnum',
  full_name='protobuf_unittest.TestAllTypes.NestedEnum',
  filename='NestedEnum',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOO', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_TESTALLTYPES_NESTEDMESSAGE = descriptor.Descriptor(
  name='NestedMessage',
  full_name='protobuf_unittest.TestAllTypes.NestedMessage',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bb', full_name='protobuf_unittest.TestAllTypes.NestedMessage.bb', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTALLTYPES_OPTIONALGROUP = descriptor.Descriptor(
  name='OptionalGroup',
  full_name='protobuf_unittest.TestAllTypes.OptionalGroup',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestAllTypes.OptionalGroup.a', index=0,
      number=17, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTALLTYPES_REPEATEDGROUP = descriptor.Descriptor(
  name='RepeatedGroup',
  full_name='protobuf_unittest.TestAllTypes.RepeatedGroup',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestAllTypes.RepeatedGroup.a', index=0,
      number=47, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTALLTYPES = descriptor.Descriptor(
  name='TestAllTypes',
  full_name='protobuf_unittest.TestAllTypes',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='optional_int32', full_name='protobuf_unittest.TestAllTypes.optional_int32', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_int64', full_name='protobuf_unittest.TestAllTypes.optional_int64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_uint32', full_name='protobuf_unittest.TestAllTypes.optional_uint32', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_uint64', full_name='protobuf_unittest.TestAllTypes.optional_uint64', index=3,
      number=4, type=4, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_sint32', full_name='protobuf_unittest.TestAllTypes.optional_sint32', index=4,
      number=5, type=17, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_sint64', full_name='protobuf_unittest.TestAllTypes.optional_sint64', index=5,
      number=6, type=18, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_fixed32', full_name='protobuf_unittest.TestAllTypes.optional_fixed32', index=6,
      number=7, type=7, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_fixed64', full_name='protobuf_unittest.TestAllTypes.optional_fixed64', index=7,
      number=8, type=6, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_sfixed32', full_name='protobuf_unittest.TestAllTypes.optional_sfixed32', index=8,
      number=9, type=15, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_sfixed64', full_name='protobuf_unittest.TestAllTypes.optional_sfixed64', index=9,
      number=10, type=16, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_float', full_name='protobuf_unittest.TestAllTypes.optional_float', index=10,
      number=11, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_double', full_name='protobuf_unittest.TestAllTypes.optional_double', index=11,
      number=12, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_bool', full_name='protobuf_unittest.TestAllTypes.optional_bool', index=12,
      number=13, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_string', full_name='protobuf_unittest.TestAllTypes.optional_string', index=13,
      number=14, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_bytes', full_name='protobuf_unittest.TestAllTypes.optional_bytes', index=14,
      number=15, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optionalgroup', full_name='protobuf_unittest.TestAllTypes.optionalgroup', index=15,
      number=16, type=10, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_nested_message', full_name='protobuf_unittest.TestAllTypes.optional_nested_message', index=16,
      number=18, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_foreign_message', full_name='protobuf_unittest.TestAllTypes.optional_foreign_message', index=17,
      number=19, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_nested_enum', full_name='protobuf_unittest.TestAllTypes.optional_nested_enum', index=18,
      number=21, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_foreign_enum', full_name='protobuf_unittest.TestAllTypes.optional_foreign_enum', index=19,
      number=22, type=14, cpp_type=8, label=1,
      default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_string_piece', full_name='protobuf_unittest.TestAllTypes.optional_string_piece', index=20,
      number=24, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\002')),
    descriptor.FieldDescriptor(
      name='optional_cord', full_name='protobuf_unittest.TestAllTypes.optional_cord', index=21,
      number=25, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\001')),
    descriptor.FieldDescriptor(
      name='repeated_int32', full_name='protobuf_unittest.TestAllTypes.repeated_int32', index=22,
      number=31, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_int64', full_name='protobuf_unittest.TestAllTypes.repeated_int64', index=23,
      number=32, type=3, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_uint32', full_name='protobuf_unittest.TestAllTypes.repeated_uint32', index=24,
      number=33, type=13, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_uint64', full_name='protobuf_unittest.TestAllTypes.repeated_uint64', index=25,
      number=34, type=4, cpp_type=4, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_sint32', full_name='protobuf_unittest.TestAllTypes.repeated_sint32', index=26,
      number=35, type=17, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_sint64', full_name='protobuf_unittest.TestAllTypes.repeated_sint64', index=27,
      number=36, type=18, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_fixed32', full_name='protobuf_unittest.TestAllTypes.repeated_fixed32', index=28,
      number=37, type=7, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_fixed64', full_name='protobuf_unittest.TestAllTypes.repeated_fixed64', index=29,
      number=38, type=6, cpp_type=4, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_sfixed32', full_name='protobuf_unittest.TestAllTypes.repeated_sfixed32', index=30,
      number=39, type=15, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_sfixed64', full_name='protobuf_unittest.TestAllTypes.repeated_sfixed64', index=31,
      number=40, type=16, cpp_type=2, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_float', full_name='protobuf_unittest.TestAllTypes.repeated_float', index=32,
      number=41, type=2, cpp_type=6, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_double', full_name='protobuf_unittest.TestAllTypes.repeated_double', index=33,
      number=42, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_bool', full_name='protobuf_unittest.TestAllTypes.repeated_bool', index=34,
      number=43, type=8, cpp_type=7, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_string', full_name='protobuf_unittest.TestAllTypes.repeated_string', index=35,
      number=44, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_bytes', full_name='protobuf_unittest.TestAllTypes.repeated_bytes', index=36,
      number=45, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeatedgroup', full_name='protobuf_unittest.TestAllTypes.repeatedgroup', index=37,
      number=46, type=10, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_nested_message', full_name='protobuf_unittest.TestAllTypes.repeated_nested_message', index=38,
      number=48, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_foreign_message', full_name='protobuf_unittest.TestAllTypes.repeated_foreign_message', index=39,
      number=49, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_nested_enum', full_name='protobuf_unittest.TestAllTypes.repeated_nested_enum', index=40,
      number=51, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_foreign_enum', full_name='protobuf_unittest.TestAllTypes.repeated_foreign_enum', index=41,
      number=52, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_string_piece', full_name='protobuf_unittest.TestAllTypes.repeated_string_piece', index=42,
      number=54, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\002')),
    descriptor.FieldDescriptor(
      name='repeated_cord', full_name='protobuf_unittest.TestAllTypes.repeated_cord', index=43,
      number=55, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\001')),
    descriptor.FieldDescriptor(
      name='default_int32', full_name='protobuf_unittest.TestAllTypes.default_int32', index=44,
      number=61, type=5, cpp_type=1, label=1,
      default_value=41,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_int64', full_name='protobuf_unittest.TestAllTypes.default_int64', index=45,
      number=62, type=3, cpp_type=2, label=1,
      default_value=42,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_uint32', full_name='protobuf_unittest.TestAllTypes.default_uint32', index=46,
      number=63, type=13, cpp_type=3, label=1,
      default_value=43,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_uint64', full_name='protobuf_unittest.TestAllTypes.default_uint64', index=47,
      number=64, type=4, cpp_type=4, label=1,
      default_value=44,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_sint32', full_name='protobuf_unittest.TestAllTypes.default_sint32', index=48,
      number=65, type=17, cpp_type=1, label=1,
      default_value=-45,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_sint64', full_name='protobuf_unittest.TestAllTypes.default_sint64', index=49,
      number=66, type=18, cpp_type=2, label=1,
      default_value=46,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_fixed32', full_name='protobuf_unittest.TestAllTypes.default_fixed32', index=50,
      number=67, type=7, cpp_type=3, label=1,
      default_value=47,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_fixed64', full_name='protobuf_unittest.TestAllTypes.default_fixed64', index=51,
      number=68, type=6, cpp_type=4, label=1,
      default_value=48,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_sfixed32', full_name='protobuf_unittest.TestAllTypes.default_sfixed32', index=52,
      number=69, type=15, cpp_type=1, label=1,
      default_value=49,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_sfixed64', full_name='protobuf_unittest.TestAllTypes.default_sfixed64', index=53,
      number=70, type=16, cpp_type=2, label=1,
      default_value=-50,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_float', full_name='protobuf_unittest.TestAllTypes.default_float', index=54,
      number=71, type=2, cpp_type=6, label=1,
      default_value=51.5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_double', full_name='protobuf_unittest.TestAllTypes.default_double', index=55,
      number=72, type=1, cpp_type=5, label=1,
      default_value=52000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_bool', full_name='protobuf_unittest.TestAllTypes.default_bool', index=56,
      number=73, type=8, cpp_type=7, label=1,
      default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_string', full_name='protobuf_unittest.TestAllTypes.default_string', index=57,
      number=74, type=9, cpp_type=9, label=1,
      default_value="hello",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_bytes', full_name='protobuf_unittest.TestAllTypes.default_bytes', index=58,
      number=75, type=12, cpp_type=9, label=1,
      default_value="world",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_nested_enum', full_name='protobuf_unittest.TestAllTypes.default_nested_enum', index=59,
      number=81, type=14, cpp_type=8, label=1,
      default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_foreign_enum', full_name='protobuf_unittest.TestAllTypes.default_foreign_enum', index=60,
      number=82, type=14, cpp_type=8, label=1,
      default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_string_piece', full_name='protobuf_unittest.TestAllTypes.default_string_piece', index=61,
      number=84, type=9, cpp_type=9, label=1,
      default_value="abc",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\002')),
    descriptor.FieldDescriptor(
      name='default_cord', full_name='protobuf_unittest.TestAllTypes.default_cord', index=62,
      number=85, type=9, cpp_type=9, label=1,
      default_value="123",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\001')),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _TESTALLTYPES_NESTEDENUM,
  ],
  options=None)


_FOREIGNMESSAGE = descriptor.Descriptor(
  name='ForeignMessage',
  full_name='protobuf_unittest.ForeignMessage',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='c', full_name='protobuf_unittest.ForeignMessage.c', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTREQUIRED = descriptor.Descriptor(
  name='TestRequired',
  full_name='protobuf_unittest.TestRequired',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestRequired.a', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy2', full_name='protobuf_unittest.TestRequired.dummy2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='b', full_name='protobuf_unittest.TestRequired.b', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy4', full_name='protobuf_unittest.TestRequired.dummy4', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy5', full_name='protobuf_unittest.TestRequired.dummy5', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy6', full_name='protobuf_unittest.TestRequired.dummy6', index=5,
      number=6, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy7', full_name='protobuf_unittest.TestRequired.dummy7', index=6,
      number=7, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy8', full_name='protobuf_unittest.TestRequired.dummy8', index=7,
      number=8, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy9', full_name='protobuf_unittest.TestRequired.dummy9', index=8,
      number=9, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy10', full_name='protobuf_unittest.TestRequired.dummy10', index=9,
      number=10, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy11', full_name='protobuf_unittest.TestRequired.dummy11', index=10,
      number=11, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy12', full_name='protobuf_unittest.TestRequired.dummy12', index=11,
      number=12, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy13', full_name='protobuf_unittest.TestRequired.dummy13', index=12,
      number=13, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy14', full_name='protobuf_unittest.TestRequired.dummy14', index=13,
      number=14, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy15', full_name='protobuf_unittest.TestRequired.dummy15', index=14,
      number=15, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy16', full_name='protobuf_unittest.TestRequired.dummy16', index=15,
      number=16, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy17', full_name='protobuf_unittest.TestRequired.dummy17', index=16,
      number=17, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy18', full_name='protobuf_unittest.TestRequired.dummy18', index=17,
      number=18, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy19', full_name='protobuf_unittest.TestRequired.dummy19', index=18,
      number=19, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy20', full_name='protobuf_unittest.TestRequired.dummy20', index=19,
      number=20, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy21', full_name='protobuf_unittest.TestRequired.dummy21', index=20,
      number=21, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy22', full_name='protobuf_unittest.TestRequired.dummy22', index=21,
      number=22, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy23', full_name='protobuf_unittest.TestRequired.dummy23', index=22,
      number=23, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy24', full_name='protobuf_unittest.TestRequired.dummy24', index=23,
      number=24, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy25', full_name='protobuf_unittest.TestRequired.dummy25', index=24,
      number=25, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy26', full_name='protobuf_unittest.TestRequired.dummy26', index=25,
      number=26, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy27', full_name='protobuf_unittest.TestRequired.dummy27', index=26,
      number=27, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy28', full_name='protobuf_unittest.TestRequired.dummy28', index=27,
      number=28, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy29', full_name='protobuf_unittest.TestRequired.dummy29', index=28,
      number=29, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy30', full_name='protobuf_unittest.TestRequired.dummy30', index=29,
      number=30, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy31', full_name='protobuf_unittest.TestRequired.dummy31', index=30,
      number=31, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy32', full_name='protobuf_unittest.TestRequired.dummy32', index=31,
      number=32, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c', full_name='protobuf_unittest.TestRequired.c', index=32,
      number=33, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTREQUIREDFOREIGN = descriptor.Descriptor(
  name='TestRequiredForeign',
  full_name='protobuf_unittest.TestRequiredForeign',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='optional_message', full_name='protobuf_unittest.TestRequiredForeign.optional_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='repeated_message', full_name='protobuf_unittest.TestRequiredForeign.repeated_message', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dummy', full_name='protobuf_unittest.TestRequiredForeign.dummy', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTFOREIGNNESTED = descriptor.Descriptor(
  name='TestForeignNested',
  full_name='protobuf_unittest.TestForeignNested',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='foreign_nested', full_name='protobuf_unittest.TestForeignNested.foreign_nested', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTEMPTYMESSAGE = descriptor.Descriptor(
  name='TestEmptyMessage',
  full_name='protobuf_unittest.TestEmptyMessage',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTREALLYLARGETAGNUMBER = descriptor.Descriptor(
  name='TestReallyLargeTagNumber',
  full_name='protobuf_unittest.TestReallyLargeTagNumber',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestReallyLargeTagNumber.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bb', full_name='protobuf_unittest.TestReallyLargeTagNumber.bb', index=1,
      number=268435455, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTRECURSIVEMESSAGE = descriptor.Descriptor(
  name='TestRecursiveMessage',
  full_name='protobuf_unittest.TestRecursiveMessage',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestRecursiveMessage.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='i', full_name='protobuf_unittest.TestRecursiveMessage.i', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTMUTUALRECURSIONA = descriptor.Descriptor(
  name='TestMutualRecursionA',
  full_name='protobuf_unittest.TestMutualRecursionA',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='bb', full_name='protobuf_unittest.TestMutualRecursionA.bb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTMUTUALRECURSIONB = descriptor.Descriptor(
  name='TestMutualRecursionB',
  full_name='protobuf_unittest.TestMutualRecursionB',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestMutualRecursionB.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='optional_int32', full_name='protobuf_unittest.TestMutualRecursionB.optional_int32', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTDUPFIELDNUMBER_FOO = descriptor.Descriptor(
  name='Foo',
  full_name='protobuf_unittest.TestDupFieldNumber.Foo',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestDupFieldNumber.Foo.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTDUPFIELDNUMBER_BAR = descriptor.Descriptor(
  name='Bar',
  full_name='protobuf_unittest.TestDupFieldNumber.Bar',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestDupFieldNumber.Bar.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTDUPFIELDNUMBER = descriptor.Descriptor(
  name='TestDupFieldNumber',
  full_name='protobuf_unittest.TestDupFieldNumber',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='a', full_name='protobuf_unittest.TestDupFieldNumber.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='foo', full_name='protobuf_unittest.TestDupFieldNumber.foo', index=1,
      number=2, type=10, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bar', full_name='protobuf_unittest.TestDupFieldNumber.bar', index=2,
      number=3, type=10, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTNESTEDMESSAGEHASBITS_NESTEDMESSAGE = descriptor.Descriptor(
  name='NestedMessage',
  full_name='protobuf_unittest.TestNestedMessageHasBits.NestedMessage',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='nestedmessage_repeated_int32', full_name='protobuf_unittest.TestNestedMessageHasBits.NestedMessage.nestedmessage_repeated_int32', index=0,
      number=1, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nestedmessage_repeated_foreignmessage', full_name='protobuf_unittest.TestNestedMessageHasBits.NestedMessage.nestedmessage_repeated_foreignmessage', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_TESTNESTEDMESSAGEHASBITS = descriptor.Descriptor(
  name='TestNestedMessageHasBits',
  full_name='protobuf_unittest.TestNestedMessageHasBits',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='optional_nested_message', full_name='protobuf_unittest.TestNestedMessageHasBits.optional_nested_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTCAMELCASEFIELDNAMES = descriptor.Descriptor(
  name='TestCamelCaseFieldNames',
  full_name='protobuf_unittest.TestCamelCaseFieldNames',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='PrimitiveField', full_name='protobuf_unittest.TestCamelCaseFieldNames.PrimitiveField', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='StringField', full_name='protobuf_unittest.TestCamelCaseFieldNames.StringField', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='EnumField', full_name='protobuf_unittest.TestCamelCaseFieldNames.EnumField', index=2,
      number=3, type=14, cpp_type=8, label=1,
      default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='MessageField', full_name='protobuf_unittest.TestCamelCaseFieldNames.MessageField', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='StringPieceField', full_name='protobuf_unittest.TestCamelCaseFieldNames.StringPieceField', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\002')),
    descriptor.FieldDescriptor(
      name='CordField', full_name='protobuf_unittest.TestCamelCaseFieldNames.CordField', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\001')),
    descriptor.FieldDescriptor(
      name='RepeatedPrimitiveField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedPrimitiveField', index=6,
      number=7, type=5, cpp_type=1, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='RepeatedStringField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedStringField', index=7,
      number=8, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='RepeatedEnumField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedEnumField', index=8,
      number=9, type=14, cpp_type=8, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='RepeatedMessageField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedMessageField', index=9,
      number=10, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='RepeatedStringPieceField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedStringPieceField', index=10,
      number=11, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\002')),
    descriptor.FieldDescriptor(
      name='RepeatedCordField', full_name='protobuf_unittest.TestCamelCaseFieldNames.RepeatedCordField', index=11,
      number=12, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\010\001')),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTFIELDORDERINGS = descriptor.Descriptor(
  name='TestFieldOrderings',
  full_name='protobuf_unittest.TestFieldOrderings',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='my_string', full_name='protobuf_unittest.TestFieldOrderings.my_string', index=0,
      number=11, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='my_int', full_name='protobuf_unittest.TestFieldOrderings.my_int', index=1,
      number=1, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='my_float', full_name='protobuf_unittest.TestFieldOrderings.my_float', index=2,
      number=101, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTEXTREMEDEFAULTVALUES = descriptor.Descriptor(
  name='TestExtremeDefaultValues',
  full_name='protobuf_unittest.TestExtremeDefaultValues',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='escaped_bytes', full_name='protobuf_unittest.TestExtremeDefaultValues.escaped_bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      default_value="\000\001\007\010\014\n\r\t\013\\\'\"\376",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='large_uint32', full_name='protobuf_unittest.TestExtremeDefaultValues.large_uint32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=4294967295,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='large_uint64', full_name='protobuf_unittest.TestExtremeDefaultValues.large_uint64', index=2,
      number=3, type=4, cpp_type=4, label=1,
      default_value=18446744073709551615,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='small_int32', full_name='protobuf_unittest.TestExtremeDefaultValues.small_int32', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=-2147483647,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='small_int64', full_name='protobuf_unittest.TestExtremeDefaultValues.small_int64', index=4,
      number=5, type=3, cpp_type=2, label=1,
      default_value=-9223372036854775807,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='utf8_string', full_name='protobuf_unittest.TestExtremeDefaultValues.utf8_string', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value="\341\210\264",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FOOREQUEST = descriptor.Descriptor(
  name='FooRequest',
  full_name='protobuf_unittest.FooRequest',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_FOORESPONSE = descriptor.Descriptor(
  name='FooResponse',
  full_name='protobuf_unittest.FooResponse',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BARREQUEST = descriptor.Descriptor(
  name='BarRequest',
  full_name='protobuf_unittest.BarRequest',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_BARRESPONSE = descriptor.Descriptor(
  name='BarResponse',
  full_name='protobuf_unittest.BarResponse',
  filename='unittest_basic.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_TESTALLTYPES.fields_by_name['optionalgroup'].message_type = _TESTALLTYPES_OPTIONALGROUP
_TESTALLTYPES.fields_by_name['optional_nested_message'].message_type = _TESTALLTYPES_NESTEDMESSAGE
_TESTALLTYPES.fields_by_name['optional_foreign_message'].message_type = _FOREIGNMESSAGE
_TESTALLTYPES.fields_by_name['optional_nested_enum'].enum_type = _TESTALLTYPES_NESTEDENUM
_TESTALLTYPES.fields_by_name['optional_foreign_enum'].enum_type = _FOREIGNENUM
_TESTALLTYPES.fields_by_name['repeatedgroup'].message_type = _TESTALLTYPES_REPEATEDGROUP
_TESTALLTYPES.fields_by_name['repeated_nested_message'].message_type = _TESTALLTYPES_NESTEDMESSAGE
_TESTALLTYPES.fields_by_name['repeated_foreign_message'].message_type = _FOREIGNMESSAGE
_TESTALLTYPES.fields_by_name['repeated_nested_enum'].enum_type = _TESTALLTYPES_NESTEDENUM
_TESTALLTYPES.fields_by_name['repeated_foreign_enum'].enum_type = _FOREIGNENUM
_TESTALLTYPES.fields_by_name['default_nested_enum'].enum_type = _TESTALLTYPES_NESTEDENUM
_TESTALLTYPES.fields_by_name['default_foreign_enum'].enum_type = _FOREIGNENUM
_TESTREQUIREDFOREIGN.fields_by_name['optional_message'].message_type = _TESTREQUIRED
_TESTREQUIREDFOREIGN.fields_by_name['repeated_message'].message_type = _TESTREQUIRED
_TESTFOREIGNNESTED.fields_by_name['foreign_nested'].message_type = _TESTALLTYPES_NESTEDMESSAGE
_TESTRECURSIVEMESSAGE.fields_by_name['a'].message_type = _TESTRECURSIVEMESSAGE
_TESTMUTUALRECURSIONA.fields_by_name['bb'].message_type = _TESTMUTUALRECURSIONB
_TESTMUTUALRECURSIONB.fields_by_name['a'].message_type = _TESTMUTUALRECURSIONA
_TESTDUPFIELDNUMBER.fields_by_name['foo'].message_type = _TESTDUPFIELDNUMBER_FOO
_TESTDUPFIELDNUMBER.fields_by_name['bar'].message_type = _TESTDUPFIELDNUMBER_BAR
_TESTNESTEDMESSAGEHASBITS_NESTEDMESSAGE.fields_by_name['nestedmessage_repeated_foreignmessage'].message_type = _FOREIGNMESSAGE
_TESTNESTEDMESSAGEHASBITS.fields_by_name['optional_nested_message'].message_type = _TESTNESTEDMESSAGEHASBITS_NESTEDMESSAGE
_TESTCAMELCASEFIELDNAMES.fields_by_name['EnumField'].enum_type = _FOREIGNENUM
_TESTCAMELCASEFIELDNAMES.fields_by_name['MessageField'].message_type = _FOREIGNMESSAGE
_TESTCAMELCASEFIELDNAMES.fields_by_name['RepeatedEnumField'].enum_type = _FOREIGNENUM
_TESTCAMELCASEFIELDNAMES.fields_by_name['RepeatedMessageField'].message_type = _FOREIGNMESSAGE

class TestAllTypes(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class NestedMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTALLTYPES_NESTEDMESSAGE
  
  class OptionalGroup(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTALLTYPES_OPTIONALGROUP
  
  class RepeatedGroup(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTALLTYPES_REPEATEDGROUP
  DESCRIPTOR = _TESTALLTYPES

class ForeignMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOREIGNMESSAGE

class TestRequired(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREQUIRED

class TestRequiredForeign(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREQUIREDFOREIGN

class TestForeignNested(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTFOREIGNNESTED

class TestEmptyMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTEMPTYMESSAGE

class TestReallyLargeTagNumber(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREALLYLARGETAGNUMBER

class TestRecursiveMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTRECURSIVEMESSAGE

class TestMutualRecursionA(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMUTUALRECURSIONA

class TestMutualRecursionB(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMUTUALRECURSIONB

class TestDupFieldNumber(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Foo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTDUPFIELDNUMBER_FOO
  
  class Bar(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTDUPFIELDNUMBER_BAR
  DESCRIPTOR = _TESTDUPFIELDNUMBER

class TestNestedMessageHasBits(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class NestedMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TESTNESTEDMESSAGEHASBITS_NESTEDMESSAGE
  DESCRIPTOR = _TESTNESTEDMESSAGEHASBITS

class TestCamelCaseFieldNames(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTCAMELCASEFIELDNAMES

class TestFieldOrderings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTFIELDORDERINGS

class TestExtremeDefaultValues(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTEXTREMEDEFAULTVALUES

class FooRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOOREQUEST

class FooResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOORESPONSE

class BarRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BARREQUEST

class BarResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BARRESPONSE


_TESTSERVICE = descriptor.ServiceDescriptor(
  name='TestService',
  full_name='protobuf_unittest.TestService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='Foo',
    full_name='protobuf_unittest.TestService.Foo',
    index=0,
    containing_service=None,
    input_type=_FOOREQUEST,
    output_type=_FOORESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Bar',
    full_name='protobuf_unittest.TestService.Bar',
    index=1,
    containing_service=None,
    input_type=_BARREQUEST,
    output_type=_BARRESPONSE,
    options=None,
  ),
])

class TestService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TESTSERVICE
class TestService_Stub(TestService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TESTSERVICE

